; generated by Slic3r 1.2.9 on 2016-03-29 at 12:55:51

; external perimeters extrusion width = 0.30mm
; perimeters extrusion width = 0.30mm
; infill extrusion width = 0.30mm
; solid infill extrusion width = 0.30mm
; top infill extrusion width = 0.30mm

M107
M190 S57 ; set bed temperature
G28								; home all axes (if axis shifting bug is fixed!)
G32								; execute bed Z-plane  compensation at bed.g 4 points
G10 P0 X-16 Y-3 Z0.0 S-273 R-273		; set extruder x,y offsets
M83								; set extruder to relative mode
G10 P0 S195 R160					; Set tool 0 operating and standby temperatures
T0									; select tool ZERO




G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
G1 X57.322 Y56.565 Z10

M107
G91								; Set to Relative Positioning so that we can go up a fixed distance from current position which is the end of the print
G1 Z1								; move up 1mm from where we were when the print ended
G90								; Set to Absolute Positioning 
G10 P0 X0.0 Y0.0 Z0.0 S-273 R-273	; Set tool 0 operating and standby temperatures  to negative 273 C means swtiched off, and zero all offsets
G4 S1
G1 X120  Y135						; move to X:120, Y:135, i.e. eject ! Note G1 X78 centers the head on the X axis, but not the extruder!
G4 S0								; wait for zero seconds?
M140 S-273							;  set bed heater  to switched off
; filament used = 4051.5mm (9.7cm3)

; avoid_crossing_perimeters = 0
; bed_shape = 0x0,140x0,140x140,0x140
; bed_temperature = 57
; before_layer_gcode = 
; bridge_acceleration = 0
; bridge_fan_speed = 100
; brim_width = 0
; complete_objects = 0
; cooling = 1
; default_acceleration = 0
; disable_fan_first_layers = 3
; duplicate_distance = 6
; end_gcode = G91								; Set to Relative Positioning so that we can go up a fixed distance from current position which is the end of the print\nG1 Z1								; move up 1mm from where we were when the print ended\nG90								; Set to Absolute Positioning \nG10 P0 X0.0 Y0.0 Z0.0 S-273 R-273	; Set tool 0 operating and standby temperatures  to negative 273 C means swtiched off, and zero all offsets\nG1 X120  Y135						; move to X:120, Y:135, i.e. eject ! Note G1 X78 centers the head on the X axis, but not the extruder!\nG4 S0								; wait for zero seconds?\nM140 S-273							;  set bed heater  to switched off
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; fan_always_on = 1
; fan_below_layer_time = 60
; filament_colour = #FFFFFF
; filament_diameter = 1.75
; first_layer_acceleration = 0
; first_layer_bed_temperature = 57
; first_layer_extrusion_width = 0.5
; first_layer_speed = 50%
; first_layer_temperature = 0
; gcode_arcs = 0
; gcode_comments = 0
; gcode_flavor = reprap
; infill_acceleration = 0
; infill_first = 0
; layer_gcode = 
; max_fan_speed = 100
; max_print_speed = 80
; max_volumetric_speed = 0
; min_fan_speed = 100
; min_print_speed = 10
; min_skirt_length = 0
; notes = 
; nozzle_diameter = 0.3
; only_retract_when_crossing_perimeters = 1
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; perimeter_acceleration = 0
; post_process = 
; pressure_advance = 0
; resolution = 0
; retract_before_travel = 2
; retract_layer_change = 1
; retract_length = 3.5
; retract_length_toolchange = 10
; retract_lift = 0
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 40
; skirt_distance = 10
; skirt_height = 1
; skirts = 1
; slowdown_below_layer_time = 20
; spiral_vase = 0
; standby_temperature_delta = -5
; start_gcode = G28								; home all axes (if axis shifting bug is fixed!)\nG32								; execute bed Z-plane  compensation at bed.g 4 points\nG10 P0 X-16 Y-3 Z0.0 S-273 R-273		; set extruder x,y offsets\nM83								; set extruder to relative mode\nG10 P0 S195 R160					; Set tool 0 operating and standby temperatures\nT0									; select tool ZERO\n\n\n\n
; temperature = 0
; threads = 2
; toolchange_gcode = 
; travel_speed = 150
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; vibration_limit = 0
; wipe = 0
; z_offset = 0
; dont_support_bridges = 1
; extrusion_width = 0.3
; first_layer_height = 0.3
; infill_only_where_needed = 0
; interface_shells = 0
; layer_height = 0.2
; raft_layers = 0
; seam_position = random
; support_material = 0
; support_material_angle = 0
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0.3
; support_material_interface_extruder = 1
; support_material_interface_layers = 3
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_pattern = pillars
; support_material_spacing = 2.5
; support_material_speed = 40
; support_material_threshold = 0
; xy_size_compensation = -0.05
; bottom_solid_layers = 3
; bridge_flow_ratio = 1
; bridge_speed = 30
; external_fill_pattern = concentric
; external_perimeter_extrusion_width = 0.3
; external_perimeter_speed = 30
; external_perimeters_first = 1
; extra_perimeters = 1
; fill_angle = 45
; fill_density = 10%
; fill_pattern = honeycomb
; gap_fill_speed = 20
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.3
; infill_overlap = 15%
; infill_speed = 40
; overhangs = 1
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.3
; perimeter_speed = 30
; perimeters = 3
; small_perimeter_speed = 30
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.3
; solid_infill_speed = 30
; thin_walls = 1
; top_infill_extrusion_width = 0.3
; top_solid_infill_speed = 30
; top_solid_layers = 3
